"""
Django settings for pft project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pft import env
from pft.config import django_app, drf, spectacular

BASE_DIR = env.BASE_DIR
SECRET_KEY = env.SECRET_KEY
DEBUG = env.DEBUG
ALLOWED_HOSTS = env.ALLOWED_HOSTS

INSTALLED_APPS = django_app.INSTALLED_APPS
MIDDLEWARE = django_app.MIDDLEWARE
TEMPLATES = django_app.TEMPLATES
AUTH_PASSWORD_VALIDATORS = django_app.AUTH_PASSWORD_VALIDATORS

REST_FRAMEWORK = drf.REST_FRAMEWORK
SIMPLE_JWT = drf.SIMPLE_JWT

SPECTACULAR_SETTINGS = spectacular.SPECTACULAR_SETTINGS

ROOT_URLCONF = 'pft.urls'

WSGI_APPLICATION = 'pft.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.PFT_DB_NAME,
        'USER': env.PFT_DB_USER,
        'PASSWORD': env.PFT_DB_PASSWORD,
        'HOST': env.PFT_DB_HOST,
        'PORT': env.PFT_DB_PORT,
    }
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/' 
MEDIA_ROOT= os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'user.PFTUser'
