# Generated by Django 5.2 on 2025-04-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pftuser',
            options={'verbose_name': 'PFT user', 'verbose_name_plural': 'PFT users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User profile', 'verbose_name_plural': 'User profiles'},
        ),
        migrations.AlterModelTable(
            name='pftuser',
            table='pft_user',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='profile',
        ),
    ]
